stages:
  - stage: StageBuild
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - bash: |
              set -ex
              sudo add-apt-repository ppa:haxe/haxe3.4 -y
              sudo apt update -y
              sudo apt install -qqy haxe jq
              sudo npm install -g tfx-cli
            displayName: Install dependencies
          - bash: |
              set -ex
              haxelib setup ~/haxelib
              haxelib install HaxeTool/build.hxml --always
            displayName: Install Haxe libraries
          - bash: make
            displayName: Build
          - publish: output
            artifact: vsix
          - bash: |
              set -ex
              [ "`jq -r .version vss-extension.json`" == "`jq -r '.version | "\(.Major).\(.Minor).\(.Patch)"' HaxeTool/task.json`" ]
              [ "`jq -r .version vss-extension.json`" == "`jq -r .version HaxeTool/package.json`" ]
              [ "`jq -r .version HaxeTool/package.json`" == "`jq -r .version HaxeTool/package-lock.json`" ]
            displayName: Check version
  - stage: StagePublish
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), variables['AZURE_TOKEN'])
    jobs:
      - job: Publish
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - bash: |
              set -ex
              sudo apt update -y
              sudo apt install -qqy jq
              sudo npm install -g tfx-cli
            displayName: Install dependencies
          - download: current
            artifact: vsix
          - bash: make publish
            env:
              AZURE_TOKEN: $(AZURE_TOKEN)
            displayName: publish extension
